version: '3.4'

services:
  catalogdb:
     container_name: catalogdb
     restart: always
     ports:
      - 27107:27107
     volumes:
      - D:\delete\Databases\Mangodb:/data/db

  basketdb:
     container_name: basketdb
     restart: always
     ports:
      - 6379:6379

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    ports:
      - "8000:80"
    depends_on:
      - catalogdb
 
  portainer:
    container_name: portainer
    ports:
      - 8080:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - D:\delete\Databases\portainer:/data

  basket.api:
    container_name: basket.api  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings:ConnectionString=basketdb:6379
    ports:
      - "8001:80"
    depends_on:
      - basketdb

